### ISSUE TITLE
Change the default `<mr-surface>` spawning behavior

### ISSUE THREAD

**Issue by lobau** [Volumetrics-io/MR.js#100]
Currently, when you enter XR, you have to do some gesture to get the <mr-surface> to display (the pinch and drag or something). In my setup at least, it's pretty finicky, and I often end up with the surface being very small and far from me, or being horizontal, angled, etc
I think the default behavior should be that the surface appears right in front of you, at a reasonable hard-coded size (over-writable of course).
The idea of letting the user snap it on walls or tables should probably be an add-on you can enable, instead of the default.

**Comment by michaelthatsit** [comment]
Just saw the weird horizontal bug, that shouldn't be happening. I'll try to tackle it after I've fixed the https solution.
