### ISSUE TITLE
<mr-img> changes the image colors

### ISSUE THREAD

**Issue by lobau** [Volumetrics-io/MR.js#146]
See examples

![image](https://github.com/Volumetrics-io/MR.js/assets/6750584/01b0620a-e0d9-4b55-93ac-1bcf7a544d53)
![image](https://github.com/Volumetrics-io/MR.js/assets/6750584/34b8087d-4b19-4de0-8a3f-776bdf094e6c)

It seems the lightning is messing up the images. I think by default the images should have their default colors, at least with the default lightning.

**Comment by michaelthatsit** [comment]
I've switched to MeshStandardMaterial which helps the image react to light a little better, but we also need to choose which default lighting we want to commit to. It's going to impact the white balance of any image you pass in. 

I've also fixed the hand clipping/shadow issue.
