### ISSUE TITLE
Streamline / optimize the MR.js build / packaging process.

### ISSUE THREAD

**Issue by jakimfett** [Volumetrics-io/MR.js#54]
Running the MR.js build process generates some warnings about the size of specific outputs:
```
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  build.js (840 KiB)
  65ac97703679d0300d84.module.wasm (1.34 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (840 KiB)
      build.js
```

This ticket is for refining the packaging to reduce the size of the output.

**Comment by michaelthatsit** [comment]
Any ideas on how we can bring it down? I removed some dependencies. My next thought was to remove RAPIER from the bundle and ask users to import it separately.
