### ISSUE TITLE
Text size shouldn't be based on the window height

### ISSUE THREAD

**Issue by lobau** [Volumetrics-io/MR.js#60]
https://github.com/Volumetrics-io/MR.js/assets/6750584/368f41b6-cfa2-4e8a-aa3e-f73e6067e10e

Currently the text seems to be based on the height of the window
`<mr-texteditor text-style="size: 0.02; vertical: top" padding="0.01">`

To emulate normal, 2d websites, the text size should be fixed (or based on width breakpoints)

**Comment by michaelthatsit** [comment]
I'm taking this up now as there are other things I'd like to address in the TextSystem.

I'm not sure we can do pixels as our absolute units given that the windows aren't technically screens, so they don't have a fixed pixel density.

We could support inches, cm, and mm, as absolute units. 

which relative units would be the highest priority? vh, vw, and vmax would be pretty simple.
