### ISSUE TITLE
reduce logging noise

### ISSUE THREAD

**Issue by lobau** [Volumetrics-io/MR.js#63]
![image](https://github.com/Volumetrics-io/MR.js/assets/6750584/2918aaa5-a4e9-4213-8e61-0aed3f8e0ed2)

By default, MR.js spam the console a lot.
Adding a verbose flag to <mr-app> might be a good solution to disable it by default.

**Comment by michaelthatsit** [comment]
This should be resolved in the latest update.

**Comment by michaelthatsit** [comment]
Resolved in latest update.
