### ISSUE TITLE
Support data attributes on MR custom elements

### ISSUE THREAD

**Issue by lobau** [Volumetrics-io/MR.js#64]
I was hoping data-attributes would be supported natively.
I wanted to store a default color so I can switch the color on hover and switch back to the default color on hover-end. It seems [data attributes](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes) are not supported on <mr-….> elements.

Sample code:

```
<body>
  <mr-app camera="camera: orthographic">
    <mr-surface>
      <mr-container>
        <mr-row>
          <mr-panel margin="0 0.03" default-color="black"></mr-panel>
          <mr-panel margin="0 0.03" default-color="red"></mr-panel>
          <mr-panel margin="0 0.03" default-color="blue"></mr-panel>
        </mr-row>
      </mr-container>
    </mr-surface>
  </mr-app>
</body>

<script>
  let panels = document.querySelectorAll('mr-panel')

  for (const panel of panels) {
    panel.color = panel.dataset.defaultColor;

    panel.onHover = (event) => {
      switch (event.type) {
        case 'hover-start':
          panel.color = "yellow";
          break;

        case 'hover-end':
          panel.color = panel.dataset.defaultColor;
          break;

        default:
          break;
      }
    }
  }
</script>

</html>

```

**Comment by michaelthatsit** [comment]
@lobau I'm pretty sure you need to prepend the data attribute with `data-`

https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes

**Comment by lobau** [comment]
oh lol you're correct. Not the case for customelements, but it is for standard data attributes.
