### ISSUE TITLE
CSS Support

### ISSUE THREAD

**Issue by michaelthatsit** [Volumetrics-io/MR.js#73]
inline styling isn't a great or scalable experience. we should find a way to at least partially support css for things like color, fonts, and layout.

**Comment by michaelthatsit** [comment]
- preloading fonts: https://developer.mozilla.org/en-US/docs/Web/API/Document/fonts
- loading style per entity: https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle

**Comment by Mstanic05** [comment]
Can you assign this to me!

**Comment by michaelthatsit** [comment]
Assuming you dropped off on this one. Gonna continue with documenting this issue a little more.

Initial Requirements:
- font family
- font size
- color
- font style (might not be supported in troika text directly)
- font weight (might not be supported in troika text directly)
- width
- maxWidth
- minWidth
- height
- maxHeight
- minHeight
- background
- border-radius
- padding
- margin

**Comment by michaelthatsit** [comment]
Hey @lobau can you go through this list and lemme know what we should immediately support?

https://protectwise.github.io/troika/troika-three-text/#supported-properties
