### ISSUE TITLE
<mr-text> doesn't support events

### ISSUE THREAD

**Issue by lobau** [Volumetrics-io/MR.js#76]
I've been trying to make a quick prototype, but it was not working. I realized that it's because <mr-text> just doesn't support click events.

example (this doesn't work):
```html
<body>
  <mr-app camera="camera: orthographic">
    <mr-surface>
      <mr-container>
        <mr-panel>
          <mr-text id="affordance">Click me</mr-text>
        </mr-panel>
      </mr-container>
    </mr-surface>
  </mr-app>
</body>

<script>
  document.querySelector('#affordance').addEventListener('click', (event) => {
    console.log("here");
  });
</script>
```

If you put the id on the parent <mr-panel>, it works, but it is unexpected

**Comment by michaelthatsit** [comment]
I had this before but disabled it The logic being that I wanted to reduce the number of physics bodies. Both texteditor and textfield should receive events. 

Should text receive the event, or it's parent? (button, panel, etc.)

**Comment by lobau** [comment]
I believe in HTML any element can receive event no? If so people might come with this expectation.
Can you check if an element has events attached to them, and only if so you add them to the physics engine?

**Comment by michaelthatsit** [comment]
This was fixed in a recent update.
