### ISSUE TITLE
directly manipulate each corner of a UI plane with border-radius

### ISSUE THREAD

**Issue by michaelthatsit** [Volumetrics-io/MR.js#85]
The current geometry implementation allows for only 1 radius which is applied to all 4 corners, ideally we should be able to apply a unique radius to each corner.

**Comment by michaelthatsit** [comment]
[Here's the UIPlane code](https://github.com/Volumetrics-io/MR.js/blob/ae7fa7b83044eb69168056c08b975b6068226d29/src/geometry/UIPlane.js#L4)

**Comment by hanbollar** [comment]
duplicate of #147, closing in favor of that one
