### ISSUE TITLE
Integrate Skyboxes as a background to a web page

### ISSUE THREAD

**Issue by Dinoel27** [Volumetrics-io/MR.js#89]
Hello:) 

Is it possible to integrate a skybox into MR.js? 

The skybox will appear in the background once the website is opened. The skybox would load/appear in the same direction as the webpage is presented to the user (top to down). The skybox can be toggled on/off. Also, the skybox could be shown as a half dome vertically or horizontally. Users can add multiple skyboxes and scroll through them as they progress on the web page. 

If skybox is a feature of a tool for creating an XR website, users should be able to import the skybox correctly. 

For now, these are all the thoughts I have

**Comment by michaelthatsit** [comment]
@lobau assigning to you since you're already working on it. it'll be cool to integrate this directly into the library 🥳
