### ISSUE TITLE
Support for GLB/GLTF and or USDZ file formats 

### ISSUE THREAD

**Issue by Dinoel27** [Volumetrics-io/MR.js#95]
Please add GLB/GLTF and USDZ file import into mr.js 

This would make file import way easier for testing and developing.

**Comment by michaelthatsit** [comment]
@hanbollar dumping this one on you as discussed

**Comment by hanbollar** [comment]
good timing @Dinoel27, i'll have pr coming soon with that ~

**Comment by lobau** [comment]
related to https://github.com/Volumetrics-io/MR.js/issues/75

**Comment by hanbollar** [comment]
GLB incoming from https://github.com/Volumetrics-io/MR.js/pull/97

others coming soon after
