### ISSUE TITLE
Ignore whitespace in <mr-text>

### ISSUE THREAD

**Issue by lobau** [Volumetrics-io/MR.js#98]
Currently `<mr-text>` respect whitespace, similarely to a `<pre>` tag in HTML.
I think it should behave like a `<p>` tag instead. As seen on the video, my code formatting keep destroying my text formatting.
I think we should ignore whitespace and support `<p>` to separate paragraphs

[Screencast from 2023-11-09 15-51-13.webm](https://github.com/Volumetrics-io/MR.js/assets/6750584/13eaf160-bcdf-466e-9979-a5fc9c251f1d)

**Comment by michaelthatsit** [comment]
This should be an easy fix. 

do you think eliminating the mr-text tag altogether is a good idea? It's not immediately intuitive how we'd accomplish it but it would be great to just infer the text. or even use h1, p, etc.

**Comment by lobau** [comment]
yeah I think if it was possible to just rely on p, h1, etc, it would be more intuitive and more readable
